### ISSUE TITLE
schematic ?

### ISSUE THREAD

**Issue by nathmo** [bigtreetech/Raspberry-Pad#16]
hey, would it be possible to release the schematic of the board ?
a PDF on this repo would be nice

**Comment by sl1pkn07** [comment]
and display datasheet. 0500a800 (need to be edit)  not exist in the market (for replace spare part

greetings

**Comment by gamelaster** [comment]
@bigtreetech any updates?

**Comment by gamelaster** [comment]
https://github.com/bigtreetech/Raspberry-Pad/blob/master/Pad5/Hardware/BIGTREETECH%20Raspberry%20pad%205-SCH.pdf
